---
abstract: 'SPARQL/Update serializer for RDF::Trine'
author:
  - 'konstantin baierer <kba@cpan.org>'
build_requires:
  LWP::Protocol::PSGI: 0
  Pod::Readme: 0
  Pod::Select: 0
  RDF::Endpoint: 0.04
  SUPER: 0
  String::Diff: 0
  Term::ANSIColor: 0
  YAML::XS: 0
configure_requires:
  Module::Build: 0.38
  Pod::Readme: 0
  Pod::Select: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Trine-Serializer-SparqlUpdate
provides:
  RDF::Trine::Serializer::SparqlUpdate:
    file: lib/RDF/Trine/Serializer/SparqlUpdate.pm
    version: 0.002
requires:
  IO::Handle::Iterator: 0
  Moose: 2.0
  RDF::Trine: 0.136
  Try::Tiny: 0.09
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
